FROM node:22

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Remove unnecessary source files AFTER verifying the build
RUN rm -rf ./src

EXPOSE 3001

CMD ["npm", "run", "start:prod"]

# docker build -t hanpoom-test-project-prod-docker -f Dockerfile.prod .
# docker run -p 3000:3000 hanpoom-test-project-prod-docker